version: '3.6'


services:
    style2paints:
        build: .
        ports:
            - 8000:80
        volumes:
            - ./results:/app/style2paints/V3/server/results
            - ./V3/server:/app/V3/server
