version: '3.6'


services:
    style2paints:
        build: .
        command: sh -c "cd /app/V3/server && python debug.py -cpu"
        ports:
            - 8000:80
        environment:
            - CUDA_VISIBLE_DEVICES=""
        volumes:
            - ./results:/app/style2paints/V3/server/results
            - ./V3/server:/app/V3/server
            - ./models:/app/V3/server/models
